#!/bin/bash
# Author: Walied Arulandu
# Date Created: 2021/12/06 10:54:00
# Description: This script will output "This is a test message" on the screen
# Date Modified: YYYY/MM/DD 00:00:00

echo
echo This script will runs basic administrative tasks
echo 
top -n 1
echo 
df -h
echo 
free -m
echo 
uptime
echo 
iostat
echo
