#!/bin/bash
# Author: Walied Arulandu
# Date Created: 2021/12/06 11:32:41
# Description: This script will run basic linux tasks
# Date Modified: 2021/12/06 11:21:42

echo
echo This is script will run a few basic tasks 
echo 
pwd
echo
ls
echo
whoami
echo
date
echo
cal
echo
touch ../trash/a ../trash/b ../trash/c 
echo End of script
