#!/bin/bash
# Script: check_disk_while_loop
# Author: Walied Arulandu
# Date Created: Wed Jan  5 07:49:18 2022
# Description: This script will check disk capacity against a specified threshold and report usage above the threshold amount.
# Date Modified: Wed Jan  5 07:49:18 2022
#
#
threshold=50

df -H | grep -vE '^Filesystem|tmpfs|cdrom|loop|udev' | awk {'print $5, $1'} | while read output
do
  disk_used_percentages=$( echo $output | awk {'print $1'} | cut -d'%' -f1 )
  partition=$( echo $output | awk {'print $2'} )

  if [ $disk_used_percentages -ge $threshold ]
  then
    echo Running out of disk space on $partition. It is now at $disk_used_percentages% on $(hostname) as of today $( date "+%a %b %__d" )
  fi
done
