#!/bin/bash
# Script: create_user
# Author: Walied Arulandu
# Date Created: Tue Jan  4 05:43:16 2022 
# Description: This script will create a user account.
# Date Modified: Tue Jan  4 05:43:16 2022 
#
#
echo What is the username?:
read user_name
echo

grep -q $user_name /etc/passwd
  if [ $? -eq 0 ]
  then
    echo Error -- user $user_name already exists!
    echo Please choose a different username.
    echo
    exit 0
  fi

useradd $user_name
echo $user_name user account has been created.
