#!/bin/bash
# Author: Walied Arulandu
# Date Created: Mon Dec 27 22:34:55 2021
# Description: This script will create multiple files specified by input.
# Date Modified: Mon Dec 27 22:34:55 2021 

#
echo How many files do you want?
read input

echo
echo Enter the prefix for the file name: 
read prefix

echo
echo Provide the suffix
read suffix

for i in $(seq 1 $input)
do
  touch ~/projects/trash/$prefix.$i.$suffix
done
