#!/bin/bash
# Script: create_user
# Author: Walied Arulandu
# Date Created: Tue Jan  4 05:43:16 2022 
# Description: This script will create a user account.
# Date Modified: Tue Jan  4 05:43:16 2022 
#
#
echo What is the username?:
read user_name
echo

# Check if user already exists.

grep -q $user_name /etc/passwd
  if [ $? -eq 0 ]
  then
    echo Error -- user $user_name already exists!
    echo Please choose a different username.
    echo
    exit 0
  fi

# Requesting a description for the user. 
echo "Please provide a description for the user:"
read description
echo

# Creating the new user.
useradd $user_name -c "$description"
echo $user_name user account has been created.
