#!/bin/bash
# Script: create_user
# Author: Walied Arulandu
# Date Created: Tue Jan  4 05:43:16 2022 
# Description: This script will create a user account.
# Date Modified: Tue Jan  4 05:43:16 2022 
#
#
echo What is the username?:
read user_name
echo

# Check if user already exists.
grep -q $user_name /etc/passwd
  if [ $? -eq 0 ]
  then
    echo Error -- user account $user_name already exists!
    echo Please choose a different username.
    echo
    exit 0
  fi

# Requesting a description for the user. 
echo Please provide a description for the user:
read description
echo

# Requesting a user ID.
echo "Do you want to give a user ID (y/n)?"
read answer_uid
echo

if [ $answer_uid == y ]
then
  echo Enter the user ID:
  read user_id
  echo
  
  # Check if user id number already exists  
  grep -q $user_id /etc/passwd
  if [ $? -eq 0 ]
  then
    echo Error -- user ID $user_id already exists!
    echo Please choose a different user ID.
    echo
    exit 0
  fi

  # Creating the new user with a user id.
  useradd $user_name -c "$description" -u $user_id
  echo $user_name user account has been created with user id $user_id.

elif [ $answer_uid == n ]
then
  # Creating the new user.
  useradd $user_name -c "$description"
  echo $user_name user account has been created without a user id.
fi
