#!/bin/bash
# Script: disable_inactive_users
# Author: Walied Arulandu
# Date Created: Tue Jan  4 07:39:25 2022
# Description: This script will disable inactive users.
# Date Modified: Tue Jan  4 07:39:25 2022 
#
#
user_accounts=$(lastlog | tail -n+2 | grep 'test' | awk {'print $1'})

for user_id in $user_accounts
do
  # Lock the accounts
  usermod -L $user_id
done
