#!/bin/bash
# Script: disable_inactive_users
# Author: Walied Arulandu
# Date Created: Tue Jan  4 07:39:25 2022
# Description: This script will disable inactive users using xargs.
# Date Modified: Tue Jan  4 07:39:25 2022 
#
#
lastlog | tail -n+2 | grep 'test' | awk {'print $1'} | xargs -I {} usermod -L {}
