#!/bin/bash
# Author: Walied Arulandu
# Date Created: 2021/12/08 21:44:00
# Description: This script will create 5 files using the touch command.
# Date Modified: YYYY/MM/DD 00:00:00


LOGDIR=~/projects/trash

for i in {1..5}
do
  touch ${LOGDIR}/$i
done
