#!/bin/bash
# Author: Walied Arulandu
# Date Created: 2021/12/10 13:02:15
# Description: This script will get the timestamps for a given file.
# Date Modified: YYYY/MM/DD 00:00:00

file_system=/dev/sda5

# Passing the file name into script at the command line by using the built in $1 shell parameter makes it so much more quicker and easier.
inode_id=$(ls -i $1 | awk {'print $1'})

# The following echo is used for debugging.
#echo $inode_id

sudo debugfs -R 'stat <'$inode_id'>' $file_system
