#!/bin/bash
# Author: Walied Arulandu
# Date Created: 2021/12/07 22:05:00
# Description: This script will check for the existence of a log file and display the result.
# Date Modified: YYYY/MM/DD 00:00:00

# File Operations:
#
# -s	file exists and is not empty
# -f	file exists and is not a directory
# -d	directory exists
# -x	file is executable
# -w	file is writable
# -r	file is readable

# Check if the file exists. 
if [ -e ~/projects/trash/error.txt ]
  then
    echo The file exists
  else
    echo The file does not exist
fi

# Check if the file exists and is not empty. 
if [ -s ~/projects/trash/error.txt ]
  then
    echo The file exists and is not empty
  else
    echo The file does not exist or is not empty
fi

# Check if the file exists and is not a directory. 
if [ -f ~/projects/trash/error.txt ]
  then
    echo The file exists and is not a directory
  else
    echo The file does not exist or is a diretory
fi

# Check if the directory exists. 
if [ -d ~/projects/trash/errored ]
  then
    echo The directory exists
  else
    echo The directory does not exist
fi

# Check if the file is executable. 
if [ -x ~/projects/trash/error.txt ]
  then
    echo The file is executable
  else
    echo The file is not executable
fi

# Check if the file is writable. 
if [ -w ~/projects/trash/error.txt ]
  then
    echo The file is writable
  else
    echo The file is not writable
fi

# Check if the file is readable. 
if [ -r ~/projects/trash/error.txt ]
  then
    echo The file is readable
  else
    echo The file is not readable
fi
