#!/bin/bash
# Author: Walied Arulandu
# Date Created: 2021/12/07 22:05:00
# Description: This script will check for the existence of a log file and output the result on the screeni.
# Date Modified: YYYY/MM/DD 00:00:00

# Check if file exist 
if [ -e ~/projects/trash/error.txt ]
  then
  echo "File exist"
  else
  echo "File does not exist"
fi

