#!/bin/bash
# Author: Walied Arulandu
# Date Created: 2021/12/07 21:51:00
# Description: This script will check the count and display a message on screen.
# Date Modified: YYYY/MM/DD 00:00:00

count=100
if [ $count -eq 100 ]
then
  echo The count is 100
else
  echo The count is not 100
fi
