#!/bin/bash
# Script: last_logged_users
# Author: Walied Arulandu
# Date Created: Mon Jan  3 08:06:43 2022 
# Description: This script will list users logged in by date.
# Date Modified: Mon Jan  3 08:06:43 2022 

# the date command on this system adds a leading zero for padding on the day of the month. 
# We, therefore we use the date command to format the output.
#
#current_date=$( date | awk {'print $1, $3'} )

current_date=$( date "+%a %b %__d" )

# For deugging output purposes: Cannot cannot use day of the month because it has a leading zero
# and the last command does not use the leading zero in single diggit day of the month. 
#
#echo $current_date

last | grep "$current_date" 
