#!/bin/bash
# Script: last_logged_users
# Author: Walied Arulandu
# Date Created: Mon Jan  3 08:06:43 2022 
# Description: This script will list users logged in by date.
# Date Modified: Mon Jan  3 08:06:43 2022 

# The date command on this system adds leading zeros for padding to the day of the month. 
# We, therefore format the output of date to add spaces replacing the leading zeros.

current_date=$( date "+%a %b %__d" )

# For deugging purposes.  
#echo $current_date

last | grep "$current_date" 
