#!/bin/bash
# Author: Walied Arulandu
# Date Created: 2021/12/09 04:35:00
# Description: This script will list all users on the system.
# Date Modified: YYYY/MM/DD 00:00:00

i=1

for username in $(awk -F : {'print $1'} /etc/passwd)
do
  echo Username $((i++)): $username
done
