#!/bin/bash
#---------------------------------------------------------------------------------------#
# Script: search_in_compressed_files
# Author: Walied Arulandu
# Created on: Fri 04 Mar 2022 02:56:22 SAST
# Description: This will search from a given list and report if they are found inside of compressed files.
# Modified on: Fri 04 Mar 2022 02:56:22 SAST
#--------------------------------------------------------------------------------------#
#
#

Path_to_product='/var/opt/teradata/packages/patches'

Folder_name='sws_OS_move'

File_list='teradata-vmf	
teradata-osmigration
virt-utils
teradata-biosutils 	
teradata-diskutils 	
teradata-gsctools 	
teradata-osutils 	
teradata-linux-config
bynet'

echo
for file_name in "$Path_to_product/$Folder_name/"
do
  for file in File_list
  do
    tar -tzvf  "$Path_to_product_path/$Folder_name/file_name" |grep $file
  done
done
