#!/bin/bash
#---------------------------------------------------------------------------------------#
# Script: search_in_compressed_files
# Author: Walied Arulandu
# Created on: Fri 04 Mar 2022 02:56:22 SAST
# Description: Search a given list of file names within compressed files.
# Modified on: Fri 04 Mar 2022 02:56:22 SAST
#--------------------------------------------------------------------------------------#
#
#

Path_to_product='/var/opt/teradata/packages/patches'

Folder_name='sws_OS_move'

File_list='teradata-vmf	
teradata-osmigration
virt-utils
teradata-biosutils 	
teradata-diskutils 	
teradata-gsctools 	
teradata-osutils 	
teradata-linux-config
bynet'

Compressed_file_count=0

echo
for file_name in $Path_to_product/$Folder_name/*.gz
do
  for file in $File_list
  do
    tar -tvzf $file_name | grep $file
  done
  ((++Comppressed_file_count))
done

echo Searched through $Comppressed_file_count compressed files 
