#!/bin/bash
#---------------------------------------------------------------------------------------#
# Script: teradat_checks
# Author: Walied Arulandu
# Created on: Wed 12 Jan 2022 10:55:11 SAST
# Description: This will health check.
# Modified on: Wed 12 Jan 2022 10:55:11 SAST
#--------------------------------------------------------------------------------------#
#
#
