#!/bin/bash
# Author: Walied Arulandu
# Date Created: Sun Dec 19 22:56:12 2021
# Description: This script will create a file with a user specified create date.
# Date Modified: YYYY/MM/DD 00:00:00

#
file_path=~/projects/trash/

echo Specify the day '(Mon-Sun)':
read the_day

echo Specify the date '(1-31)':
read the_date

echo Specify the Month '(e.g. March)':
read the_month

echo Specify day the year '(e.g. 2018)':
read the_year

echo Specify the hour '(01-23)':
read the_hour

echo Specify the minutes '(01-59)':
read the_minutes

echo Specify the seconds '(01-59)':
read the_seconds

echo Specify a name for the file: 
read file_name

absolute_date=$the_day', '$the_date' '$the_month' '$the_year' '$the_hour':'$the_minutes':'$the_seconds 

echo The create date will be $absolute_date as specified.

touch -d "$absolute_date" $file_path$file_name
